"""add_image_support

Revision ID: 004b54bd914e
Revises: 350115ea15b8
Create Date: 2025-11-22 20:34:19.654454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004b54bd914e'
down_revision: Union[str, Sequence[str], None] = '350115ea15b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('xref', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('colorspace', sa.String(length=20), nullable=True),
    sa.Column('has_transparency', sa.Boolean(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_page', 'book_images', ['book_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_book_images_book_id'), 'book_images', ['book_id'], unique=False)
    op.add_column('books', sa.Column('image_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('books', sa.Column('has_images', sa.Boolean(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_books_has_images'), 'books', ['has_images'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_has_images'), table_name='books')
    op.drop_column('books', 'has_images')
    op.drop_column('books', 'image_count')
    op.drop_index(op.f('ix_book_images_book_id'), table_name='book_images')
    op.drop_index('idx_book_page', table_name='book_images')
    op.drop_table('book_images')
    # ### end Alembic commands ###
